SQSMaster: SQSMaster Class Reference
SQSMaster Class Reference
the main class for the master server
#include <SQSMaster.h>
Public Member Functions
SQSMaster ()
SQSMaster (int client, int dataNode, int connTimeout, int msgTimeout)
void dispatchMessage (std::string remoteNode, int remotePort, std::string request)
dispatch the giving request to the remote node.
virtual ~SQSMaster ()
bool init ()
do all the necessary things to start the master returns true if every goes fine, otherwise false
void start ()
start listening on master.
void onDataNodeRecv (struct evhttp_request *req)
invoke when a request from data node received The request url should be this kind: http:hostName:hostPort/operation?param1=value1&param2=value2
void onClientReqRecv (struct evhttp_request *req)
invoke when a request from client received if the request's path is '/getavailablehost', it will check the available data nodes and return one, i.e. " nodeName: localhost nodePort: 8080 " if no data nodes available, it will return a message: "No Data Node available..."
Private Attributes
int clientPort
port number for the client connection
int dataNodePort
port number for the data node connection
int connectionTimeout
default connection time out
MsgLock * pLock
lock for message
std::vector< DataNode > mDataNodes
all available data nodes
Logger * logger
logger for message processing
HeartBeat * pBeat
Heart beat checker.
Detailed Description
the main class for the master server
Definition at line 166 of file SQSMaster.h.
Constructor & Destructor Documentation
SQSMaster::SQSMaster () [inline]
Definition at line 197 of file SQSMaster.h.
SQSMaster::SQSMaster (int client, int dataNode, int connTimeout, int msgTimeout) [inline]
Definition at line 199 of file SQSMaster.h.
virtual SQSMaster::~SQSMaster () [inline, virtual]
Definition at line 211 of file SQSMaster.h.
References pLock, and MsgLock::Stop().
Member Function Documentation
void SQSMaster::dispatchMessage (std::string remoteNode, int remotePort, std::string request)
dispatch the giving request to the remote node.
Parameters:
remoteNode the remote node name
remotePort the remote port
request the url path that containing all the datas, i.e. '/createQueue?queueName=queue1'
Bug:
there is a bug. It will block for a long time sometimes on some circumstances
Definition at line 176 of file SQSMaster.cpp.
References dispatchMsgCallBack().
bool SQSMaster::init ()
do all the necessary things to start the master returns true if every goes fine, otherwise false
Definition at line 594 of file SQSMaster.cpp.
References ClientCallBack(), and DataNodeCallBack().
Referenced by main().
void SQSMaster::onClientReqRecv (struct evhttp_request * req)
invoke when a request from client received if the request's path is '/getavailablehost', it will check the available data nodes and return one, i.e. " nodeName: localhost nodePort: 8080 " if no data nodes available, it will return a message: "No Data Node available..."
Todo:
You can change the return messages!
all the other request are unrecognizable and will return a message: "Unrecognized request......"
Parameters:
req the object containing all the necessary messages
Definition at line 562 of file SQSMaster.cpp.
References GET_AVAILABLE_HOST.
Referenced by ClientCallBack().
void SQSMaster::onDataNodeRecv (struct evhttp_request * req)
invoke when a request from data node received The request url should be this kind: http:hostName:hostPort/operation?param1=value1&param2=value2
Warning:
All the requests should contain its node name and node port which is used to communicate with the master, i.e. http:hostName:hostPort/operation?nodeName=value1&nodePort=value2.
The redirect message is the same with the log message
1 To create a queue, the uri should be: http:hostName:hostPort/createQueue?nodeName=value1&nodePort=value2&queueName=value3. The log and redirect message will be: /createQueue?queueName=value1 If succeeds, the return message is "Create Queue Request Accepted!"
2 To delete a queue, the uri should be: http:hostName:hostPort/deleteQueue?nodeName=value1&nodePort=value2&queueName=value3. The log and redirect message will be: /deleteQueue?queueName=value1 If succeeds, the return message is "Delete Queue Request Accepted!"
3 To put a message, the url should be: http:hostName:hostPort/putMessage?nodeName=value1&nodePort=value2&queueName=value3&message=value4&mId=value5. The log and redirect message will be: /putMessage?queueName=value1&message=value2&mId=value3 If succeeds, the return message is "Put message Request Accepted!"
4 To delete a message, the url should be: http:hostName:hostPort/deleteMessage?nodeName=value1&nodePort=value2&queueName=value3&mId=value5. The log and redirect message will be: /deleteMessage?queueName=value1&mId=value3 If succeeds, the return message is "Delete message Request Accepted!"
5 To get a message, the url should be: http:hostName:hostPort/getMessage?nodeName=value1&nodePort=value2&queueName=value3&mId=value5. If succeeds, the return message is "Success", otherwise "Fail".
6 To get a recovery mode, the url should be: http:hostName:hostPort/recovery?nodeName=value1&nodePort=value2&logsize=val4. If succeeds, the return message is the log messages.
7 To join it, the url should be: http:hostName:hostPort/join?nodeName=value1&nodePort=value2&publicNodeName=val3&publicNodePort=val4. If succeeds, the return message is "Welcome to join us!".
Parameters:
req the object containing all the necessary messages
Bug:
if adds "delete url_path;delete url_query;", it will tell me double free the memory. So I do not free it. But who does this job?
Definition at line 189 of file SQSMaster.cpp.
References CREATE_QUEUE, DEL_QUEUE, DELETE_MSG, EMPTY_PATH, GET_MSG, JOIN_TEAM, LOG_SIZE, MSG, MSG_ID, NODE_NAME, NODE_PORT, PUBLIC_NODE_NAME, PUBLIC_NODE_PORT, PUT_MSG, QUEUE_NAME, and RECOVERY.
Referenced by DataNodeCallBack().
void SQSMaster::start ()
start listening on master.
Make sure you have called init() and init() returns true before you can call this method
Definition at line 613 of file SQSMaster.cpp.
Referenced by main().
Member Data Documentation
int SQSMaster::clientPort [private]
port number for the client connection
Definition at line 171 of file SQSMaster.h.
int SQSMaster::connectionTimeout [private]
default connection time out
Definition at line 179 of file SQSMaster.h.
int SQSMaster::dataNodePort [private]
port number for the data node connection
Definition at line 175 of file SQSMaster.h.
Logger* SQSMaster::logger [private]
logger for message processing
Definition at line 191 of file SQSMaster.h.
std::vector<DataNode> SQSMaster::mDataNodes [private]
all available data nodes
Definition at line 187 of file SQSMaster.h.
HeartBeat* SQSMaster::pBeat [private]
Heart beat checker.
Definition at line 195 of file SQSMaster.h.
MsgLock* SQSMaster::pLock [private]
lock for message
Definition at line 183 of file SQSMaster.h.
Referenced by ~SQSMaster().
The documentation for this class was generated from the following files:
src/SQSMaster.h
src/SQSMaster.cpp