SQSMaster: EventChain Class Reference
EventChain Class Reference
timeout chain class - the timeout process core
#include <MsgLock.h>
Public Member Functions
EventChain ()
virtual ~EventChain ()
void Run ()
start handling event chain, please do not call it directly, call Start() instead
bool Start ()
call it to start process event chain
bool Stop ()
call it to stop process event chain.
void Schedule (Event *e)
schedule a new event
void Cancel (Event *e)
cancel an event
Private Attributes
Event * head
head event in the chain
pthread_t pid
the thread id the do the event process
pthread_cond_t qready
condition var to avoid overhead loop
pthread_mutex_t qlock
mutex to avoid racing
Friends
void Cleanup (void *arg)
helper method to deal with dead lock.
Detailed Description
timeout chain class - the timeout process core
Definition at line 72 of file MsgLock.h.
Constructor & Destructor Documentation
EventChain::EventChain () [inline]
Definition at line 95 of file MsgLock.h.
virtual EventChain::~EventChain () [inline, virtual]
Definition at line 97 of file MsgLock.h.
References head, and Event::next.
Member Function Documentation
void EventChain::Cancel (Event * e)
cancel an event
Parameters:
e the event to be canceled
if event not found, just free the parameter e else free both the parameter e and the matching event
Definition at line 28 of file MsgLock.cpp.
References Event::next.
void EventChain::Run ()
start handling event chain, please do not call it directly, call Start() instead
Definition at line 127 of file MsgLock.cpp.
References Cleanup().
Referenced by startThread().
void EventChain::Schedule (Event * e)
schedule a new event
Parameters:
e the event to be scheduled
Definition at line 83 of file MsgLock.cpp.
References Event::join_time, Event::next, and Event::sched_time.
bool EventChain::Start ()
call it to start process event chain
Returns:
true if successfully start otherwise false
Definition at line 57 of file MsgLock.cpp.
References startThread().
bool EventChain::Stop ()
call it to stop process event chain.
Please keep it in mind that you call this method only on condition you have to or on terminate for it will not only stop the event chain, but also free the chain list.
Returns:
true if successfully stop otherwise false
Definition at line 66 of file MsgLock.cpp.
References Event::next.
Friends And Related Function Documentation
void Cleanup (void * arg) [friend]
helper method to deal with dead lock.
It just unlock the mutex
Definition at line 120 of file MsgLock.cpp.
Member Data Documentation
Event* EventChain::head [private]
head event in the chain
Definition at line 77 of file MsgLock.h.
Referenced by ~EventChain().
pthread_t EventChain::pid [private]
the thread id the do the event process
Definition at line 81 of file MsgLock.h.
pthread_mutex_t EventChain::qlock [private]
mutex to avoid racing
Definition at line 89 of file MsgLock.h.
Referenced by Cleanup().
pthread_cond_t EventChain::qready [private]
condition var to avoid overhead loop
Definition at line 85 of file MsgLock.h.
The documentation for this class was generated from the following files:
src/MsgLock.h
src/MsgLock.cpp