SQSMaster: HeartBeat Class Reference
HeartBeat Class Reference
heart beat handling class with the data nodes
#include <SQSMaster.h>
Public Member Functions
HeartBeat (long scheTime)
virtual ~HeartBeat ()
void AddDataNode (DataNode node)
add a data node the the data node list and start regular heart beat
void CancelDataNode (DataNode node)
cancel the data node and remove it from the data node list
bool IsNodeAlive (DataNode node)
tell whether the data node is still alive if it is no longer alive, this method will remove it from the data node list
Private Member Functions
struct evhttp_request * doRequest (std::string dataNode, int port)
send a simple http heart beat request to the giving data node and return its response.
Private Attributes
long cycle
the heart beat cycle in millisecond
std::vector< DataNode * > clients
data node list
Friends
void * RegularCheck (void *arg)
do the regular check for a giving data node
Detailed Description
heart beat handling class with the data nodes
Definition at line 109 of file SQSMaster.h.
Constructor & Destructor Documentation
HeartBeat::HeartBeat (long scheTime) [inline]
Definition at line 126 of file SQSMaster.h.
virtual HeartBeat::~HeartBeat () [inline, virtual]
Definition at line 127 of file SQSMaster.h.
References clients.
Member Function Documentation
void HeartBeat::AddDataNode (DataNode node)
add a data node the the data node list and start regular heart beat
Definition at line 118 of file SQSMaster.cpp.
References Param::instance, Param::node, DataNode::Recycle(), and RegularCheck().
void HeartBeat::CancelDataNode (DataNode node)
cancel the data node and remove it from the data node list
Definition at line 150 of file SQSMaster.cpp.
Referenced by RegularCheck().
struct evhttp_request * HeartBeat::doRequest (std::string dataNode, int port) [read, private]
send a simple http heart beat request to the giving data node and return its response.
return NULL if lack of memory
Definition at line 95 of file SQSMaster.cpp.
References HEARTBEAT, and heartbeat_callback().
Referenced by RegularCheck().
bool HeartBeat::IsNodeAlive (DataNode node)
tell whether the data node is still alive if it is no longer alive, this method will remove it from the data node list
Definition at line 138 of file SQSMaster.cpp.
Friends And Related Function Documentation
void* RegularCheck (void * arg) [friend]
do the regular check for a giving data node
Parameters:
arg the Param object, containing the heart beat instance and the data node object to be processed
Definition at line 38 of file SQSMaster.cpp.
Member Data Documentation
std::vector<DataNode*> HeartBeat::clients [private]
data node list
Definition at line 118 of file SQSMaster.h.
Referenced by ~HeartBeat().
long HeartBeat::cycle [private]
the heart beat cycle in millisecond
Definition at line 114 of file SQSMaster.h.
Referenced by RegularCheck().
The documentation for this class was generated from the following files:
src/SQSMaster.h
src/SQSMaster.cpp