SQSMaster: MsgLock Class Reference
MsgLock Class Reference
class to handle message lock and unlock.
#include <MsgLock.h>
Public Member Functions
MsgLock ()
MsgLock (long tmout)
bool Lock (std::string queueName, int msgId)
lock the message returns true if successfully lock, false if the message is already locked by others
bool UnLock (std::string queueName, int msgId)
unlock the message this will always return true
bool Start ()
start the event chain process.
bool Stop ()
stop the event chain process.
Private Member Functions
bool IsExist (std::string queueName, int msgId)
Whether the giving msg id in the giving queue is already lock returns true if already lock.
bool Insert (std::string queueName, int msgId)
insert the message to the lock list.
bool Del (std::string queueName, int msgId)
Delete the locked message lock it when processing.
Private Attributes
EventChain * chain_core
std::multimap< std::string, int > mDatas
locked messages,i.e.
long defaultTmout
default time out for the message lock, 5s in default
pthread_cond_t qready
pthread_mutex_t qlock
Friends
void ReleaseLock (void *arg, std::string name, int id)
call back function to do with the event process: unlock the message and delete the event from the event list
Detailed Description
class to handle message lock and unlock.
It can handle time out event automatically
Definition at line 149 of file MsgLock.h.
Constructor & Destructor Documentation
MsgLock::MsgLock () [inline]
Definition at line 184 of file MsgLock.h.
MsgLock::MsgLock (long tmout) [inline]
Definition at line 185 of file MsgLock.h.
Member Function Documentation
bool MsgLock::Del (std::string queueName, int msgId) [private]
Delete the locked message lock it when processing.
Parameters:
queueName the queue name
msgId the message id to be unlocked returns true if successfully unlock, false if message could not be found and unlocked
Definition at line 212 of file MsgLock.cpp.
References ReleaseLock().
Referenced by ReleaseLock().
bool MsgLock::Insert (std::string queueName, int msgId) [private]
insert the message to the lock list.
It will always return true
Definition at line 206 of file MsgLock.cpp.
References ReleaseLock().
bool MsgLock::IsExist (std::string queueName, int msgId) [private]
Whether the giving msg id in the giving queue is already lock returns true if already lock.
Definition at line 189 of file MsgLock.cpp.
bool MsgLock::Lock (std::string queueName, int msgId)
lock the message returns true if successfully lock, false if the message is already locked by others
Definition at line 174 of file MsgLock.cpp.
bool MsgLock::Start ()
start the event chain process.
this is for the lock time out handling
Definition at line 229 of file MsgLock.cpp.
bool MsgLock::Stop ()
stop the event chain process.
remember to call it on terminate and only once!
Definition at line 232 of file MsgLock.cpp.
Referenced by SQSMaster::~SQSMaster().
bool MsgLock::UnLock (std::string queueName, int msgId)
unlock the message this will always return true
Definition at line 185 of file MsgLock.cpp.
Friends And Related Function Documentation
void ReleaseLock (void * arg, std::string name, int id) [friend]
call back function to do with the event process: unlock the message and delete the event from the event list
Parameters:
arg the context environment, that's, the Msglock instance
name the queue name
id the message id
Definition at line 199 of file MsgLock.cpp.
Member Data Documentation
EventChain* MsgLock::chain_core [private]
Definition at line 151 of file MsgLock.h.
long MsgLock::defaultTmout [private]
default time out for the message lock, 5s in default
Definition at line 159 of file MsgLock.h.
std::multimap<std::string,int> MsgLock::mDatas [private]
locked messages,i.e.
{queue name: { id1,id2,id3}}
Definition at line 155 of file MsgLock.h.
pthread_mutex_t MsgLock::qlock [private]
Definition at line 161 of file MsgLock.h.
pthread_cond_t MsgLock::qready [private]
Definition at line 160 of file MsgLock.h.
The documentation for this class was generated from the following files:
src/MsgLock.h
src/MsgLock.cpp