SQSMaster: src/SQSMaster.cpp File Reference
SQSMaster.cpp File Reference
#include "SQSMaster.h"
#include <iostream>
#include <err.h>
#include "event.h"
#include "evhttp.h"
#include "event2/http.h"
#include <sys/time.h>
#include "Convention.h"
#include <string.h>
#include <cstdlib>
Functions
void * RegularCheck (void *arg)
void heartbeat_callback (struct evhttp_request *req, void *rsp)
void ClientCallBack (struct evhttp_request *req, void *arg)
void DataNodeCallBack (struct evhttp_request *req, void *arg)
void dispatchMsgCallBack (struct evhttp_request *req, void *arg)
Function Documentation
void ClientCallBack (struct evhttp_request * req, void * arg)
Definition at line 161 of file SQSMaster.cpp.
References SQSMaster::onClientReqRecv().
Referenced by SQSMaster::init().
void DataNodeCallBack (struct evhttp_request * req, void * arg)
Definition at line 166 of file SQSMaster.cpp.
References SQSMaster::onDataNodeRecv().
Referenced by SQSMaster::init().
void dispatchMsgCallBack (struct evhttp_request * req, void * arg)
Definition at line 171 of file SQSMaster.cpp.
Referenced by SQSMaster::dispatchMessage().
void heartbeat_callback (struct evhttp_request * req, void * rsp)
well, it takes me a long time to find you,bug! so there is one question: if the pointer is modified by another thread,how could the original thread get the newest value? seems using keyword 'volatile' doesn't work
Definition at line 78 of file SQSMaster.cpp.
Referenced by HeartBeat::doRequest().
void* RegularCheck (void * arg)
Parameters:
arg the Param object, containing the heart beat instance and the data node object to be processed
Definition at line 38 of file SQSMaster.cpp.
References HeartBeat::CancelDataNode(), HeartBeat::cycle, HeartBeat::doRequest(), Param::instance, and Param::node.
Referenced by HeartBeat::AddDataNode().